require: rubocop-rails

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
